#!/usr/bin/env node
/**
 * Synchronize built RAGE MP packages into a `server-files/` layout.
 *
 * Usage:
 *   node scripts/sync-ragemp.mjs [target]
 *
 * `target` defaults to RAGEMP_SERVER_FILES env var or `./server-files`.
 *
 * Layout produced:
 *   <target>/packages/gta-rp-core/         <- server resource (ragemp-server dist + node_modules deps)
 *   <target>/packages/gta-rp-core/package.json
 *   <target>/client_packages/gta-rp-core/  <- client_packages bundle + CEF
 *   <target>/client_packages/index.js      <- shim that requires gta-rp-core
 *   <target>/conf.json.example             <- RAGE MP server config example
 */
import { cpSync, existsSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const target = resolve(process.argv[2] || process.env.RAGEMP_SERVER_FILES || join(root, "server-files"));

const serverDist = join(root, "packages/ragemp-server/dist");
const sharedDist = join(root, "packages/shared/dist");
const clientDist = join(root, "packages/ragemp-client/dist");
const cefDist = join(root, "packages/ragemp-cef/dist");

if (!existsSync(serverDist) || !existsSync(clientDist) || !existsSync(cefDist) || !existsSync(sharedDist)) {
  console.error("Build artifacts missing. Run `npm run build` first.");
  process.exit(1);
}

const resourceServerDir = join(target, "packages/gta-rp-core");
const resourceClientDir = join(target, "client_packages/gta-rp-core");

// Wipe previous output to avoid stale files
if (existsSync(resourceServerDir)) rmSync(resourceServerDir, { recursive: true, force: true });
if (existsSync(resourceClientDir)) rmSync(resourceClientDir, { recursive: true, force: true });

mkdirSync(resourceServerDir, { recursive: true });
mkdirSync(resourceClientDir, { recursive: true });

// --- Server bundle ---
cpSync(serverDist, resourceServerDir, { recursive: true });
// Inline shared into server bundle so RAGE MP doesn't need npm install
cpSync(sharedDist, join(resourceServerDir, "node_modules/@gta-rp/shared/dist"), { recursive: true });
writeFileSync(
  join(resourceServerDir, "node_modules/@gta-rp/shared/package.json"),
  JSON.stringify({ name: "@gta-rp/shared", main: "dist/index.js", types: "dist/index.d.ts", type: "module" }, null, 2)
);
// RAGE MP resource manifest. RAGE MP looks for `package.json#main`.
writeFileSync(
  join(resourceServerDir, "package.json"),
  JSON.stringify(
    {
      name: "gta-rp-core",
      version: "0.1.0",
      type: "module",
      main: "index.js",
      dependencies: { dotenv: "^16.6.1" }
    },
    null,
    2
  )
);
// Install runtime deps in resource folder (lazy: copy from monorepo if present)
const rootNm = join(root, "node_modules");
const dotenvSrc = join(rootNm, "dotenv");
if (existsSync(dotenvSrc)) {
  cpSync(dotenvSrc, join(resourceServerDir, "node_modules/dotenv"), { recursive: true });
}

// --- Client bundle ---
cpSync(clientDist, resourceClientDir, { recursive: true });
// Inline shared for the client too (only types are used; emit is required because
// `RPEvent` constants live there as runtime values).
cpSync(sharedDist, join(resourceClientDir, "node_modules/@gta-rp/shared/dist"), { recursive: true });
writeFileSync(
  join(resourceClientDir, "node_modules/@gta-rp/shared/package.json"),
  JSON.stringify({ name: "@gta-rp/shared", main: "dist/index.js" }, null, 2)
);
// CEF assets
cpSync(cefDist, join(resourceClientDir, "cef"), { recursive: true });

// Shim entry at client_packages root so RAGE MP picks our bundle up.
writeFileSync(
  join(target, "client_packages/index.js"),
  `// Auto-generated by sync-ragemp.mjs\nrequire('./gta-rp-core/index.js');\n`
);

// --- conf.json example ---
const confPath = join(target, "conf.json.example");
if (!existsSync(confPath)) {
  writeFileSync(
    confPath,
    JSON.stringify(
      {
        announce: false,
        name: "GTA RP Core (RAGE MP)",
        gamemode: "freeroam",
        "stream-distance": 500,
        port: 22005,
        "disallow-multiple-connections-per-ip": false,
        "limit-time-of-connections-per-ip": 0,
        url: "",
        language: "ru",
        "sync-rate": 40,
        "resource-scan-thread-limit": 0,
        "max-ping": 120,
        "min-fps": 24,
        "max-packet-loss": 0.2,
        "allow-cef-debugging": true,
        "enable-nodejs": true,
        "csharp": "disabled",
        "limit-objects-creation": true,
        "players": 100,
        "voice-chat": true,
        "voice-sample-rate": 24000,
        "fastdl-host": "",
        "resources": ["gta-rp-core"]
      },
      null,
      2
    )
  );
}

console.log(`[sync-ragemp] -> ${target}`);
console.log(`  packages/gta-rp-core   (server)`);
console.log(`  client_packages/index.js + client_packages/gta-rp-core (client + CEF)`);
console.log(`  conf.json.example      (rename to conf.json)`);
